/*
Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk  Pj| is minimised; what is the value of D?

Answer: 5482660

@author Westy92
*/

public class Prob44 extends Euler
{
   public static void main(String args[])
   {
      startTiming();

      int result = 0;
      boolean found = false;
      for ( int i = 1; !found; ++i )
      {
          int n = pentagonal(i);
          for ( int j = i - 1; j > 0; --j )
          {
              int m = pentagonal(j);
              if ( isPentagonal(n - m) && isPentagonal(n + m) )
              {
                  result = n - m;
                  found = true;
                  break;
              }
          }
      }
      System.out.println(result);
      stopTiming();
   }
}
